### ISSUE TITLE
SP-816 (SP-103) added as unknown z-wave device

### ISSUE THREAD

**Issue by bexelius** [ralfvd/com.everspring#30]
Hi! I bought 5x SP-103 (modell name updated to SP-816) that is Z-wave + certified.

Link here: https://www.nexa.se/vara-produkter/zwave/sp816-rorelsevakt

1. When adding SP-103 via application the details say "Click the tamper switch behind the battery cover".  Correction is that you need to click it 3 times

2. After doing that and the application adds the device, it will be added as an unknown z-wave device and you will not be able to use it.

Could you please look into this? Would be awesome if the SP-103 worked :-)

Best regards Victor

![skarmklipp 2018-08-24 19 03 19](https://user-images.githubusercontent.com/11007317/44597608-83bc6c00-a7d0-11e8-8147-82259b3f509a.png)
![skarmklipp 2018-08-24 19 02 56](https://user-images.githubusercontent.com/11007317/44597609-83bc6c00-a7d0-11e8-98f6-ccd864cac3a3.png)
![img_20180824_190541](https://user-images.githubusercontent.com/11007317/44597739-f594b580-a7d0-11e8-9560-1e35248aa70e.jpg)
![img_20180824_190527](https://user-images.githubusercontent.com/11007317/44597740-f594b580-a7d0-11e8-87ee-b60ab5346f95.jpg)

**Comment by ralfvd** [comment]
Victor,

Can you send the node details of the SP-103 once it is connected?
Specifically Manufacturer ID, Product Type ID and Product ID.

Then I can look into it.

Thanks.

**Comment by bexelius** [comment]
"zwave": {
                "manufacturerId": 96,
                **"productTypeId": 257,** -> 1
                **"productId": 1,** -> 5
                "learnmode": {
                    "image": "/drivers/SP103/assets/learnmode.svg",
                    "instruction": {
                        **"en": "Click the tamper switch behind the battery cover",** -> Click the tamper switch behind the battery cover 3 times
                        "nl": "Druk op de tamper knop achter de batterij klep"
                    }
                },

**Comment by ralfvd** [comment]
Did you already change the code yourself to see if it then works correctly?
If so, I can easily add in the in current code and immediately push it to
the app store release ;-)

**Comment by bexelius** [comment]
Oh sorry, I did not change code. I just read you can install nodejs and install from github hehe :-D
I will do that if you dont have time to change. Thank you again for super fast replies!

**Comment by bexelius** [comment]
Ok pushed :-D

**Comment by bexelius** [comment]
Hm noob here..

✘ Homey App did not validate against level `debug`:
[
    {
        "keyword": "type",
        "dataPath": ".drivers[8].zwave.defaultConfiguration[0].id",
        "schemaPath": "#/properties/defaultConfiguration/items/properties/id/type",
        "params": {
            "type": "number"
        },
        "message": "should be number"
    }
]

**Comment by ralfvd** [comment]
I am currently getting the same issue while trying to validate the app with
the new settings. Working on it ;-)

**Comment by ralfvd** [comment]
SP816 is now on Github and pending approval in the app store. Let me know how it works.

**Comment by bexelius** [comment]
Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/drivers/AN179/driver.js:4:21)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)

Exit code: 1
Exit signal: null

**Comment by ralfvd** [comment]
If you install via GitHub, you have to add the homey-zwave driver manually
from its location: https://github.com/athombv/node-homey-zwavedriver ,
install it in node_modules/homey-zwavedriver


On 24 August 2018 at 22:16:09, Victor Bexelius (notifications@github.com)
wrote:

Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object. (/drivers/AN179/driver.js:4:21)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)

Exit code: 1
Exit signal: null

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ralfvd/com.everspring/issues/30#issuecomment-415870850>,
or mute the thread

**Comment by bexelius** [comment]
Device now added, nice! However motion detection not registered and flow not working

![skarmklipp 2018-08-24 22 54 18](https://user-images.githubusercontent.com/11007317/44607423-b6765c80-a7f0-11e8-87d7-142870330cb2.png)
![skarmklipp 2018-08-24 22 53 13](https://user-images.githubusercontent.com/11007317/44607424-b6765c80-a7f0-11e8-839b-e3ba40cf5289.png)
![skarmklipp 2018-08-24 22 52 54](https://user-images.githubusercontent.com/11007317/44607425-b70ef300-a7f0-11e8-8d9a-6a5ba5e0b7c8.png)

**Comment by bexelius** [comment]
Hi Sir,
I am just guessing here but:

1. New SP-103 modell is now z-wave + compliant

1.1 Source: https://shopcdn.textalk.se/shop/ws27/47027/art42/154548242-1b2484-ZC10-17115829.pdf

1.2 New spec info: https://shopcdn.textalk.se/shop/ws27/47027/art42/154548242-7606c0-SP816_A501112630R_20171030.pdf

2. Might be that homey-meshdriver is to be used
2.1 Source: https://github.com/athombv/node-homey-meshdriver

Again, just guessing :)

**Comment by xeterixon** [comment]
Seems like the device reports motion as a notification.
I made a quick hack in my fork, and it seems to work.
[https://github.com/xeterixon/com.everspring](https://github.com/xeterixon/com.everspring)
<img width="669" alt="screenshot 2018-10-18 at 18 30 59" src="https://user-images.githubusercontent.com/7112456/47169744-9486eb00-d304-11e8-85e4-42abd652f1b1.png">

I'll test it a bit more, and perhaps try to fix the tamper alarm, before doing a pull request.

**Comment by JMeinen69** [comment]
> install it in node_modules/homey-zwavedriver

Hi there. i'm totally new to this programming, but fun to learn. I managed to install the app to my homey. 
But now i have to instal the zwavedriver to my homey. 
Its unclear what you mean bij this. "install it in node_modules/homey-zwavedriver"
i tried the same procedure as installing the app but no luck.
Please give me a walkthrough.

**Comment by ferdw** [comment]
Is there any progress on including this one in the "official" app?
